import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";



export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className='flex flex-col min-h-screen' suppressHydrationWarning={true}>
				<div className="max-w-[480px] border-2 px-5 mx-auto">
					<div className="mobile-footer-container">
						<div className="mobile-footer-content">
							<div className="container mx-auto">
								{ children }
							</div>
						</div>
						<footer className='bg-gray-500'>
							<div className="container mx-auto py-4">
								<p className="text-center">2024 &copy; All Rights Reserved.</p>
							</div>
						</footer>
					</div>
				</div>
			</body>
		</html>
	);
}
